[project]
name = "social-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.2",
    "networkx>=3.6.1",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
